#!/usr/bin/env bash
# scripts/run-matrix.sh — wrapper around the fs-test-harness matrix
# runner that cleans up `diskimages/` on exit (success, failure,
# Ctrl-C, or any signal).
#
# Why a wrapper instead of fixing the harness directly:
# * The harness lives in `vendor/fs-test-harness/` (git submodule);
#   we don't own its lifecycle. Cleanup belongs in consumer code.
# * Each scenario in `test-matrix.json` points at
#   `diskimages/nfs-<scenario>.img`; `init-image` populates them and
#   has no opinion about who removes them. Without this trap the
#   directory accumulates ~3-5 GiB of stale images across runs.
#
# Usage: same as `vendor/fs-test-harness/scripts/run-tests.sh`. All
# arguments pass straight through. Examples:
#
#   bash scripts/run-matrix.sh                  # full matrix
#   bash scripts/run-matrix.sh basic-ro-list    # substring filter
#   bash scripts/run-matrix.sh --list           # don't run, just list
#   bash scripts/run-matrix.sh --keep-images    # skip the cleanup trap
#                                                 (handy for byte-diff
#                                                  inspection)
#
# Exit codes: pass-through from the harness runner. The trap fires
# regardless of exit code.

set -uo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root" || {
    echo "[run-matrix] fatal: cannot cd to repo_root=$repo_root" >&2
    exit 1
}

# Allow `--keep-images` to opt out of cleanup. Strip it before
# forwarding so the harness runner doesn't see an unknown flag.
keep_images=0
forwarded_args=()
for arg in "$@"; do
    case "$arg" in
        --keep-images) keep_images=1 ;;
        *) forwarded_args+=("$arg") ;;
    esac
done

# Parallel init-image creates all 42 disk images simultaneously. Placing them
# in /tmp (RAM-backed or SSD) instead of the project dir keeps I/O off slow
# storage media (SD cards, spinning disks) and avoids saturating their write
# bandwidth when many scenarios start at once.
diskimages_tmp="/tmp/ntfs-matrix-diskimages"

cleanup_diskimages() {
    # Captures the script's about-to-exit code; cleanup runs purely
    # for the side-effect (file deletion), then bash exits with this
    # code on its own. We do NOT call `exit "$rc"` here — doing that
    # inside an EXIT trap is redundant (bash exits with $? after the
    # trap returns anyway) and previously caused a re-fire when the
    # trap was also armed for signals.
    if [ "$keep_images" -eq 1 ]; then
        echo "[run-matrix] --keep-images set; leaving diskimages/ in place" >&2
        return
    fi
    # Images live in /tmp (via the symlink). Remove them, then tidy the
    # symlink and the now-empty /tmp staging dir.
    if [ -d "$diskimages_tmp" ]; then
        local count
        count=$(find "$diskimages_tmp" -maxdepth 1 -name '*.img' -type f 2>/dev/null | wc -l | tr -d ' ')
        if [ "$count" -gt 0 ]; then
            echo "[run-matrix] cleanup: removing $count image(s) from $diskimages_tmp" >&2
            find "$diskimages_tmp" -maxdepth 1 -name '*.img' -type f -delete
        fi
    fi
    rm -f "$repo_root/diskimages"
    rmdir "$diskimages_tmp" 2>/dev/null || true
}

# Single EXIT trap does all the work. The signal traps re-raise as
# `exit <128 + signum>` (the conventional code for that signal), which
# flows into the EXIT trap once. Trapping cleanup_diskimages directly
# on signals AND on EXIT would double-fire it (PR #48 review,
# greptile-apps[bot]).
trap cleanup_diskimages EXIT
trap 'exit 130' INT   # 128 + SIGINT  (2)
trap 'exit 143' TERM  # 128 + SIGTERM (15)
trap 'exit 129' HUP   # 128 + SIGHUP  (1)
trap 'exit 131' QUIT  # 128 + SIGQUIT (3)

# Create the /tmp staging dir and point diskimages/ at it. Using rm -rf
# on the existing diskimages entry (symlink or stale real dir) is safe
# here because all contents are always regenerated by init-image.
mkdir -p "$diskimages_tmp"
rm -rf "$repo_root/diskimages"
ln -s "$diskimages_tmp" "$repo_root/diskimages"

# Forward to the real runner.
bash "$repo_root/vendor/fs-test-harness/scripts/run-tests.sh" "${forwarded_args[@]+"${forwarded_args[@]}"}"
